In [195]:
from get_data_pill import *


In [196]:
# # craet a with each line is a list of pill_name in description
# path_json_root =  "/workspace/nabang1010/LBA_VAIPE/GNN/Multi_Label_Image_Recognition_with_Graph_Convolutional_Networks/data/public_train/pill/label"
# json_name_list = ["VAIPE_P_{i}_{j}.json".format(i=i, j=j) for j in range(150) for i in range(0, 1173)]
# json_name_list = os.listdir(path_json_root)
# json_name_list = sorted(json_name_list)
# json_path_list = [os.path.join(path_json_root, json_name) for json_name in json_name_list]

In [197]:
# create a list of list of pill_name in description
pill_all = []
# /workspace/nabang1010/LBA_VAIPE/GNN/Multi_Label_Image_Recognition_with_Graph_Convolutional_Networks/data/public_train/pill/label/VAIPE_P_1170_21.json
for i in range(1173):
    pill_name_set = set()
    for j in range(150):
        json_path = "/workspace/nabang1010/LBA_VAIPE/GNN/Multi_Label_Image_Recognition_with_Graph_Convolutional_Networks/data/public_train/pill/label/VAIPE_P_{i}_{j}.json".format(i=i, j=j)
        if os.path.exists(json_path):
            pill_json = json.load(open(json_path))
            for pill in pill_json:
                pill_name_set.add(pill["label"])
    pill_all.append(list(pill_name_set))
            
            

In [198]:
pill_all_string = []
for pill_line in pill_all:

    pill_line = [str(pill)+"_" for pill in pill_line]
    pill_all_string.append(" ".join(pill_line))
pill_all_string

['64_ 10_ 107_ 47_',
 '107_ 37_ 46_ 55_',
 '107_ 15_ 79_ 89_ 31_',
 '8_ 81_ 107_ 46_',
 '85_',
 '10_ 36_ 93_',
 '56_ 107_',
 '107_ 91_ 43_ 70_',
 '91_ 43_ 70_',
 '107_ 43_ 91_ 70_',
 '56_',
 '56_ 107_',
 '56_ 107_',
 '56_ 107_',
 '56_ 107_',
 '56_ 107_',
 '56_ 107_',
 '56_ 107_',
 '56_',
 '56_ 107_',
 '56_ 107_',
 '107_ 51_ 23_',
 '107_ 51_ 23_',
 '107_ 51_ 23_',
 '107_ 51_ 23_',
 '8_ 56_ 37_ 79_',
 '107_ 45_ 54_',
 '107_ 45_ 54_',
 '45_ 54_',
 '12_ 107_ 92_ 45_',
 '107_ 12_ 45_ 92_',
 '99_ 7_ 107_ 44_ 92_',
 '64_ 41_ 107_',
 '64_ 41_ 107_',
 '107_ 89_ 75_ 43_',
 '107_ 89_ 75_ 43_',
 '107_ 89_ 75_ 43_',
 '64_ 15_ 79_',
 '64_ 79_ 15_',
 '104_ 10_ 107_',
 '8_ 41_ 11_ 12_ 107_ 46_',
 '58_ 107_',
 '58_ 107_',
 '58_ 107_',
 '24_ 73_ 99_ 107_',
 '107_ 99_ 7_ 95_',
 '64_ 107_ 72_ 104_',
 '64_ 72_ 99_',
 '107_ 10_ 29_ 74_',
 '89_ 107_ 61_',
 '89_ 107_ 61_',
 '89_ 107_ 61_',
 '89_ 107_ 61_',
 '89_ 107_ 61_',
 '107_ 75_',
 '107_ 2_ 43_',
 '75_ 107_ 2_ 43_',
 '75_ 107_ 2_ 43_',
 '107_ 43_ 2_ 75_'

In [199]:
#import ifidf
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit(pill_all_string)
pill_tfidf = tfidf.transform(pill_all_string)
pill_tfidf



<1173x108 sparse matrix of type '<class 'numpy.float64'>'
	with 3251 stored elements in Compressed Sparse Row format>

In [200]:
matrix_tfidf =  pill_tfidf.toarray()
print("matrix_tfidf.shape", matrix_tfidf.shape)



matrix_tfidf.shape (1173, 108)


In [201]:
pill_all[0]

[64, 10, 107, 47]

In [202]:
len(pill_all)

1173

In [203]:
matrix_tfidf[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.2704746 , 0.4150882 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.788326  ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.36481144, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [204]:
matrix_tfidf_vocab = tfidf.vocabulary_
matrix_tfidf_vocab

{'64_': 68,
 '10_': 9,
 '107_': 8,
 '47_': 49,
 '37_': 38,
 '46_': 48,
 '55_': 58,
 '15_': 14,
 '79_': 84,
 '89_': 95,
 '31_': 32,
 '8_': 96,
 '81_': 87,
 '85_': 91,
 '36_': 37,
 '93_': 100,
 '56_': 59,
 '91_': 98,
 '43_': 45,
 '70_': 75,
 '51_': 54,
 '23_': 23,
 '45_': 47,
 '54_': 57,
 '12_': 11,
 '92_': 99,
 '99_': 106,
 '7_': 85,
 '44_': 46,
 '41_': 43,
 '75_': 80,
 '104_': 5,
 '11_': 10,
 '58_': 61,
 '24_': 24,
 '73_': 78,
 '95_': 102,
 '72_': 77,
 '29_': 29,
 '74_': 79,
 '61_': 65,
 '2_': 30,
 '26_': 26,
 '38_': 39,
 '34_': 35,
 '59_': 62,
 '62_': 66,
 '16_': 15,
 '3_': 41,
 '57_': 60,
 '28_': 28,
 '106_': 7,
 '1_': 19,
 '14_': 13,
 '50_': 53,
 '40_': 42,
 '42_': 44,
 '19_': 18,
 '18_': 17,
 '80_': 86,
 '30_': 31,
 '27_': 27,
 '60_': 64,
 '67_': 71,
 '17_': 16,
 '82_': 88,
 '68_': 72,
 '90_': 97,
 '84_': 90,
 '6_': 74,
 '97_': 104,
 '33_': 34,
 '9_': 107,
 '87_': 93,
 '103_': 4,
 '83_': 89,
 '71_': 76,
 '101_': 2,
 '63_': 67,
 '4_': 52,
 '52_': 55,
 '5_': 63,
 '22_': 22,
 '100_': 

In [205]:
matrix_adj = np.zeros((108,108))
for pill_line, matrix_tfidf_line in zip(pill_all, matrix_tfidf):
    for i in range(len(pill_line) - 1):
        for j in range(i+1, len(pill_line)):
            matrix_adj[pill_line[i], pill_line[j]] = matrix_tfidf_line[matrix_tfidf_vocab[str(pill_line[i])+"_"]] + matrix_tfidf_line[matrix_tfidf_vocab[str(pill_line[j])+"_"]]
            matrix_adj[pill_line[j], pill_line[i]] = matrix_adj[pill_line[i], pill_line[j]]
        
        

In [206]:
matrix_adj[2]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.99285686, 0.        ,
       1.08851509, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.94009225,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.05722292, 1.08228765, 0.        , 0.        ,
       1.166511  , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.40952412, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 1.25056124, 0.        , 0.        , 1.03226166,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.14289961, 0.        , 0.        , 0.99004205, 1.20162

In [207]:
# # save matrix_adj to pkl 
# import pickle
# with open('matrix_adj_pill.pkl', 'wb') as f:
#     pickle.dump(matrix_adj, f)


In [208]:
A = matrix_adj


In [243]:
np.max(matrix_adj)

1.4142135623730951

# check 

In [20]:
import pickle
num_classes = 20
import numpy as np
t = 0.4
adj_file = "../data/voc/voc_adj.pkl"
result = pickle.load(open(adj_file, 'rb'))
_adj = result['adj']
_nums = result['nums']
_nums = _nums[:, np.newaxis]
_adj = _adj / _nums
_adj[_adj < t] = 0
_adj[_adj >= t] = 1
_adj = _adj * 0.25 / (_adj.sum(0, keepdims=True) + 1e-6)
_adj = _adj + np.identity(num_classes, np.int)

/root/anaconda3/envs/mlgcn/lib/python3.7/site-packages/ipykernel_launcher.py:14: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [22]:
_adj

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.04999999,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0

In [23]:
import pickle
num_classes = 20
import numpy as np
t = 0.4
adj_file = "../data/voc/voc_adj.pkl"
result = pickle.load(open(adj_file, 'rb'))
_adj = result['adj']
_nums = result['nums']
_nums = _nums[:, np.newaxis]
_adj = _adj / _nums
_adj

array([[0.        , 0.        , 0.        , 0.00840336, 0.        ,
        0.        , 0.01680672, 0.        , 0.00420168, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.10504202,
        0.        , 0.00420168, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.00411523, 0.00823045,
        0.03292181, 0.07407407, 0.00411523, 0.03292181, 0.00411523,
        0.        , 0.00411523, 0.        , 0.02880658, 0.66255144,
        0.02057613, 0.        , 0.01234568, 0.        , 0.01234568],
       [0.        , 0.        , 0.        , 0.01212121, 0.        ,
        0.        , 0.00909091, 0.        , 0.0030303 , 0.00606061,
        0.        , 0.0030303 , 0.        , 0.        , 0.06666667,
        0.0030303 , 0.        , 0.        , 0.        , 0.        ],
       [0.01104972, 0.00552486, 0.02209945, 0.        , 0.        ,
        0.        , 0.03314917, 0.        , 0.        , 0.01104972,
        0.        , 0.01104972, 0.        , 0

In [18]:
A = torch.from_numpy(_adj).float()
D = torch.pow(A.sum(1).float(), -0.5)
D = torch.diag(D)
adj = torch.matmul(torch.matmul(A, D).t(), D)
adj

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.0000, 0.9524, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.9524, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0

In [19]:
A.sum(1).float()

tensor([1.0000, 1.0500, 1.0000, 1.0000, 1.0500, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.3000, 1.0000, 1.0500, 1.0500, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000])

In [244]:
torch.max(adj)

tensor(1.)

In [38]:
import torch
import numpy as np 
# load pickle file
import pickle
with open('/workspace/nabang1010/LBA_VAIPE/GNN/Multi_Label_Image_Recognition_with_Graph_Convolutional_Networks/checkpoint/pill_adj/matrix_adj_pill_pre.pkl', 'rb') as f:
    matrix_adj = pickle.load(f)

In [39]:
matrix_adj

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.8255951 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.16375269],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.7925274 ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.90750587],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.84786419],
       [0.8255951 , 1.16375269, 0.7925274 , ..., 0.90750587, 0.84786419,
        0.        ]])

In [40]:
# # add 1 in diagonal line
# for i in range(108):
#     matrix_adj[i,i] = 1


# add 1 in diagonal line
for i in range(108):
    matrix_adj[i,i] = 10
# normal matrix_adj
matrix_adj = matrix_adj / np.max(matrix_adj)

In [41]:
# save matrix_adj to pkl
import pickle
with open('matrix_adj_pill.pkl', 'wb') as f:
    pickle.dump(matrix_adj, f)


In [42]:
A = torch.from_numpy(matrix_adj).float()
D = torch.pow(A.sum(1).float(), -0.5)
D = torch.diag(D)
adj = torch.matmul(torch.matmul(A, D).t(), D)
adj

tensor([[0.6941, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0224],
        [0.0000, 0.5859, 0.0000,  ..., 0.0000, 0.0000, 0.0290],
        [0.0000, 0.0000, 0.3135,  ..., 0.0000, 0.0000, 0.0145],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.5510, 0.0000, 0.0220],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.3449, 0.0162],
        [0.0224, 0.0290, 0.0145,  ..., 0.0220, 0.0162, 0.1063]])